= Отчет по практическому занятию: Программирование режимов светодиодов на STM с использованием IAR 
:author: Залипаева Эвелина КЭ-201


== Цель занятия
Закрепление навыков программирования микроконтроллеров STM в среде IAR.  
Изучение принципа инверсии зависимостей (DIP) при разработке ПО для управления светодиодами.

== Оборудование
* Микроконтроллер STM32
* Среда разработки IAR Embedded Workbench
* Светодиоды и макетная плата
* Программатор ST-Link
* ПК с ОС Windows

== Теоретическая часть

=== Принцип инверсии зависимостей (DIP)
Принцип гласит:
1. Модули высокого уровня не должны зависеть от модулей низкого уровня. Оба должны зависеть от абстракций.
2. Абстракции не должны зависеть от деталей. Детали должны зависеть от абстракций.

В контексте разработки для микроконтроллеров:
- Создаются интерфейсы (абстракции) для работы с периферией
- Реализация конкретных драйверов зависит от этих интерфейсов
- Основная логика приложения зависит только от абстракций

== Практическая часть

=== Реализованные режимы светодиодов
1. Мигание с заданной частотой
2. Плавное изменение яркости (ШИМ)


=== Пример структуры проекта с DIP
[source,c]
----
// Абстракция для управления светодиодом
typedef struct {
    void (*init)(void);
    void (*set)(bool state);
    void (*toggle)(void);
} LED_Interface;

// Реализация для конкретного пина
static void STM32_LED_init(void) {
    // Инициализация GPIO
}

static void STM32_LED_set(bool state) {
    HAL_GPIO_WritePin(LED_PORT, LED_PIN, state);
}

const LED_Interface led = {
    .init = STM32_LED_init,
    .set = STM32_LED_set,
    .toggle = // реализация переключения
};

// Основной код использует только интерфейс
int main(void) {
    led.init();
    while(1) {
        led.toggle();
        delay(500);
    }
}
----

=== Реализация ШИМ с абстракцией
[source,c]
----
// Абстракция для ШИМ
typedef struct {
    void (*set_duty)(uint8_t percent);
} PWM_Interface;

// Использование в коде
void set_led_brightness(PWM_Interface pwm, uint8_t brightness) {
    pwm.set_duty(brightness);
}
----

== Выводы
1. Освоены методы управления светодиодами через регистры микроконтроллера
2. Реализованы 2 режима работы светодиодных индикаторов
3. Применен принцип DIP для создания гибкой архитектуры
4. Создана система абстракций для работы с периферией
5. Улучшены навыки отладки в среде IAR

